debug-mode: 'false'
chances:
  coal: 15
  iron: 25
  gold: 31
  redstone: 38
  lapis: 43
  diamond: 50
  obsidian: 22

staffchat-format: "&7[&bSTAFF&7]: &a$player_name$: &7$message$"
hit-delay: 8
disabledregions:
  - pvpspawn
spawn-location: {}
signs: {}