chances:
    coal: 15
    iron: 25
    gold: 31
    redstone: 38
    lapis: 43
    diamond: 50
    obsidian: 22
 
debug-mode: false
staffchat-format: "&7[&bSTAFF&7]:&a $player_name$: &7 $message$"
hit-delay: 9

fancy: true
knockback: true
tiers:
   common:
      name: "&7&lCommon Crate"
      keyName: "&7&lCommon &eKey"
      keyItem: "tripwire_hook"
      keyLore:
        - "&7Open the crate at spawn to obtain loot!"
        - "&7&oInfinicrate"
      message: "&e%player% &7opened a &7&lCommon Crate&7!"
      rewards:
        1:
            #chance: percent chance to get the reward.
            #message: Message displayed when reward has been received.
            chance: 50
            message: "&e&l1 Diamond"
            items:
                 - "diamond 1 0"
            commands:
                 - msg %player% You've got mail!!
        2:
            chance: 50
            message: "&e&l1 Dirt"
            items:
                 - "dirt 1 0"
            commands:
                 - "msg %player% Welp, that ruined it..."
   rare:
      name: "&b&lRare Crate"
      keyName: "&b&lRare &eKey"
      keyItem: "tripwire_hook"
      keyLore:
        - "&7Open the crate at spawn to obtain loot!"
        - "&7&oInfinicrate"
      message: "&e%player% &7opened a &b&lRare Crate&7!"
      rewards:
        1:
            #chance: percent chance to get the reward.
            #message: Message displayed when reward has been received.
            chance: 75
            message: "&e&l64 Emeralds"
            items:
                 - emerald 64 0
            commands:
                 - tell %player% Now go buy some stuff
        2:
            chance: 25
            message: "&a&lThe Lootcrate"
            items:
                 - diamond_sword 1 0
                 - diamond_pickaxe 1 0
                 - diamond_axe 1 0
                 - diamond_shovel 1 0
                 - diamond_hoe 1 0
                 - golden_apple 32 1
            commands:
                 - tell %player% Yay! Goodies!